import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { Snapshot } from "./snapshot.ts";
import { ms } from "./time.ts";
import type { Status } from "./report.ts";

const STATUS_ICON: Record<Status, string> = {
  done: "✅",
  progress: "🔄",
  blocked: "⛔",
  needs_input: "❓",
  idle: "💤",
};

const STATUS_WORD: Record<Status, string> = {
  done: "done",
  progress: "in progress",
  blocked: "blocked",
  needs_input: "needs your input",
  idle: "idle",
};

function ago(iso: string, now = Date.now()): string {
  const minutes = Math.max(0, Math.round((now - ms(iso)) / 60_000));
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 36) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

function bullets(items: readonly string[], limit: number): string[] {
  const shown = items.slice(0, limit).map((i) => `  - ${i}`);
  if (items.length > limit) shown.push(`  - …and ${items.length - limit} more`);
  return shown;
}

/**
 * STATE.md answers one question — "where did I leave off?" — in the time it
 * takes to read a phone screen. The design caps it at about 25 lines; so does this.
 */
export function renderState(snapshot: Snapshot): string {
  const { project } = snapshot;
  const lines: string[] = [
    `# Where we left off — ${project.config.name}`,
    "",
    `<!-- Generated by leftoff at ${snapshot.generatedAt}. Do not edit by hand. -->`,
    "",
  ];
  if (project.config.purpose) lines.push(`_${project.config.purpose}_`, "");

  if (!snapshot.lastActivityAt) {
    lines.push("No agent has reported yet.", "");
  } else {
    lines.push(`Last activity: ${ago(snapshot.lastActivityAt)} · branch \`${snapshot.git.branch}\``, "");
  }

  for (const agent of snapshot.agents) {
    const last = agent.last;
    if (!last) {
      lines.push(`**${agent.id}** — never reported`);
      continue;
    }
    const where = last.branch ? ` · \`${last.branch}\`` : "";
    lines.push(`**${agent.id}** ${STATUS_ICON[last.status]} ${STATUS_WORD[last.status]} · ${ago(last.at)}${where}`);
    if (last.done.length) lines.push(...bullets(last.done.map((d) => `done: ${d}`), 2));
    if (last.doing.length) lines.push(...bullets(last.doing.map((d) => `doing: ${d}`), 2));
    if (last.blocked.length) lines.push(...bullets(last.blocked.map((d) => `blocked: ${d}`), 2));
    if (last.decisions.length) lines.push(...bullets(last.decisions.map((d) => `decided: ${d}`), 2));
    if (last.findings.length) lines.push(...bullets(last.findings.map((d) => `found: ${d}`), 2));
    if (last.question) lines.push(`  - asks: ${last.question.text}`);
    if (last.next.length) lines.push(`  - next: ${last.next[0]}`);
    if (agent.unreportedCommits.length) {
      lines.push(`  - ⚠ ${agent.unreportedCommits.length} commit(s) after the last report`);
    }
    lines.push("");
  }

  const { todo, doing } = snapshot.tasks;
  if (todo.length || doing.length) {
    const next = [...doing, ...todo].slice(0, 3).map((t) => t.title);
    lines.push(`Backlog: ${doing.length} in progress, ${todo.length} to do — ${next.join("; ")}`, "");
  }
  if (snapshot.git.dirtyFiles) lines.push(`Uncommitted: ${snapshot.git.dirtyFiles} file(s)`, "");

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

export async function writeState(snapshot: Snapshot): Promise<string> {
  const file = snapshot.project.paths.state;
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, renderState(snapshot), "utf8");
  return file;
}

/** The terminal version of the same facts, with a little more room. */
export function renderBrief(snapshot: Snapshot): string {
  const { project } = snapshot;
  const lines = [`${project.config.name} (${project.id})`];
  if (project.config.purpose) lines.push(project.config.purpose);
  lines.push("");

  if (snapshot.agents.length === 0) {
    lines.push("No agents have reported yet. Run some work, then try again.");
    return lines.join("\n");
  }

  for (const agent of snapshot.agents) {
    const last = agent.last;
    if (!last) {
      lines.push(`${agent.id.padEnd(10)} never reported`);
      continue;
    }
    const where = last.branch ? ` · ${last.branch}` : "";
    lines.push(`${agent.id.padEnd(10)} ${STATUS_ICON[last.status]} ${STATUS_WORD[last.status]} · ${ago(last.at)}${where} · ${last.file}`);
    for (const [label, items] of [
      ["done", last.done],
      ["doing", last.doing],
      ["blocked", last.blocked],
      ["decided", last.decisions],
      ["found", last.findings],
      ["next", last.next],
    ] as const) {
      for (const item of items) lines.push(`             ${label}: ${item}`);
    }
    if (last.question) {
      lines.push(`             asks: ${last.question.text}`);
      last.question.options.forEach((o, i) => lines.push(`               ${i + 1}. ${o}`));
      if (last.question.recommend) lines.push(`               recommends: ${last.question.recommend}`);
    }
    if (last.commits.length) lines.push(`             commits: ${last.commits.join(", ")}`);
    if (agent.unreportedCommits.length) {
      lines.push(`             ⚠ ${agent.unreportedCommits.length} commit(s) since the last report`);
    }
    if (agent.pendingInbox.length) {
      lines.push(`             📥 ${agent.pendingInbox.length} undelivered message(s)`);
    }
    lines.push("");
  }

  lines.push(
    `branch ${snapshot.git.branch} · ${snapshot.git.dirtyFiles} dirty · ` +
      `${snapshot.commits.length} commit(s) in the last 14 days`,
  );
  const { todo, doing, done } = snapshot.tasks;
  if (todo.length || doing.length || done.length) {
    lines.push(`backlog: ${doing.length} in progress, ${todo.length} to do, ${done.length} done`);
    for (const t of [...doing, ...todo].slice(0, 5)) lines.push(`  - [${t.status}] ${t.title}`);
  }
  if (snapshot.costUsd > 0) lines.push(`cost (14d): $${snapshot.costUsd.toFixed(2)}`);
  return lines.join("\n");
}
